---
driver_plugin: digitalocean
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-10-04-x64
  run_list:
  - recipe[ubuntu]
- name: ubuntu-12-04-5-x64
  run_list:
  - recipe[ubuntu]
- name: ubuntu-14-04-x64
  run_list:
  - recipe[ubuntu]
- name: debian-6-0-x64
  provisioner:
    sudo: false
  busser:
    sudo: false
  run_list:
  - recipe[apt]
- name: debian-7-0-x64
  run_list:
  - recipe[apt]
- name: centos-7-0-x64
  run_list:
  - recipe[yum]
- name: centos-6-5-x64
  run_list:
  - recipe[yum]
- name: fedora-19-x64
  run_list:
  - recipe[yum]
suites:
- name: default
  run_list:
  - recipe[sslmate]
  attributes:
- name: source
  run_list:
  - recipe[sslmate]
  attributes:
    sslmate:
      install_type: source
